""""init"

Revision ID: d623d525fd3c
Revises: 814cd46aaa2e
Create Date: 2022-11-08 13:03:28.567110

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'd623d525fd3c'
down_revision = '814cd46aaa2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    op.drop_column('area', 'age')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('area', sa.Column('age', sa.INTEGER(), nullable=True))
    op.create_table('task',
    sa.Column('task_name', sa.VARCHAR(), nullable=False),
    sa.Column('task_description', sa.VARCHAR(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
